config/routes.rb
Rails.application.routes.draw do
  get 'mini_rooms/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'users/index', to: 'users#index'
  root 'mini_rooms#index'
  # root 'donations#index'
  # get 'donations/index', to: 'donations#index'
  resources :mini_rooms, only: [:new, :index, :create, :edit, :show, :update, :destroy] 
  resources :donations, only: [:new, :index, :create]

  # resources :users, only: :show
  
end

app/models/mini_room.rb
class MiniRoom < ApplicationRecord
  validates :title, presence: true
  validates :concept, presence: true
  validates :image, presence: true
  has_one_attached :image

  has_many :donation_rooms
  has_many :donations, through: :donation_rooms
  has_many :donations, dependent: :destroy
end

app/controllers/mini_rooms_controller.rb
class MiniRoomsController < ApplicationController
  def index
    @mini_rooms = MiniRoom.all
    @user = User.new
  end

  def new
    @mini_room = MiniRoom.new
  end
  
  def create
    @mini_room = MiniRoom.new(mini_room_params)
    if @mini_room.save  
    redirect_to root_path
    else
      render :new
    end
  end

  def show
    @mini_room = MiniRoom.find(params[:id])
    @donation = Donation.new
    @donations = @mini_room.donations.includes(:user)
  end

  def edit
      @mini_room = MiniRoom.find(params[:id])
      if user_signed_in? && current_user.id == @mini_room.user_id 
        redirect_to mini_room_path  unless current_user.id == @mini_room.user_id
      else
        redirect_to root_path
      end
  end

  def update
    @mini_room = MiniRoom.find(params[:id])
   if @mini_room.update(mini_room_params)
    redirect_to mini_room_path
   else
    render :edit
   end
  end

  def destroy
    mini_room = MiniRoom.find(params[:id])
    if mini_room.destroy
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def mini_room_params
    params.require(:mini_room).permit(:title, :concept, :image).merge(user_id: current_user.id)
  end
end

app/helpers/mini_rooms_helper.rb
module MiniRoomsHelper
end

app/views/mini_rooms/_donation.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @donation.name %>
      </p>
       <div class="prototype__image">
        <%= image_tag @pdonation.image %>
      </div>
      <%= form_with model: [@mini_room, @donation],local: true do |f|%>
  </div>
  </div>
</main>

app/views/mini_rooms/_form.html.erb
<%= form_with model: @mini_room, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "画像のタイトル" %><br />
    <%= f.text_field :title, id:"mini_room_title" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"mini_room_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "ミニマルの画像" %><br />
    <%= f.file_field :image, id:"mini_room_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/mini_rooms/_mini_room.html.erb
<div class="card">
  <%= link_to image_tag(mini_room.image, class: :card__img ), mini_room_path(mini_room.id), method: :get %>
  <div class="card__body">
    <%= link_to mini_room.title, mini_room_path(mini_room.id), class: :card__title%>
 <%# <%= link_to "by #{mini_room.user_id.nickname}", "/users/#{mini_room.user.id}" , class: :card__user %>
  </div>
</div>

app/views/mini_rooms/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
       <%= render partial: "form", locals: { mini_room: @mini_room } %>
    </div>
  </div>
</div>

app/views/mini_rooms/index.html.erb
<main class="main">
  <div class="inner">
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
       <%= render partial: 'mini_room', collection: @mini_rooms %> 
    </div>
  </div>
</main>

app/views/mini_rooms/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規ミニマル写真投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { mini_room: @mini_room } %>
    </div>
  </div>
</div>

app/views/mini_rooms/show.html.erb
<main class="main">
  <div class="inner">
    <div class="mini_room__wrapper">
      <p class="mini_room__hedding">
        <%= @mini_room.title %>
      </p>
      <%# <%= link_to "by #{@mini_room.user_id.nickname}", "/users/#{mini_room.user.id}", class: :mini_room__user %> 
      <% if user_signed_in? && current_user.id == @mini_room.user_id %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="mini_room__manage">
          <%= link_to "編集する", edit_mini_room_path(@mini_room.id), method: :get, class: :mini_room__btn %>
          <%= link_to "削除する", mini_room_path(@mini_room.id), method: :delete, class: :mini_room__btn %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <% end %>
      <div class="mini_room__image">
        <%= image_tag @mini_room.image %>
      </div>
      <div class="mini_room__body">
        <div class="mini_room__detail">
          <p class="detail__message">
            <%= @mini_room.concept %>
          </p>
        </div>
      </div>

    </div>
  </div>
</main>