config/routes.rb
Rails.application.routes.draw do
  get 'mini_rooms/index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'users/index', to: 'users#index'
  root 'mini_rooms#index'
  # root 'donations#index'
  # get 'donations/index', to: 'donations#index'
  resources :mini_rooms, only: [:new, :index, :create, :edit, :show, :update, :destroy] 
  resources :donations, only: [:new, :index, :create]

  # resources :users, only: :show
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniRoom38424</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

 <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("minilogo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
          <%# ログインしているときは以下を表示するようにしましょう %>
           <div class="nav__right">
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "Mini Room", new_mini_room_path, class: :nav__btn %>
              <%= link_to "Donation Room", new_donation_path, class: :nav__btn %><br><br>
               <%= link_to "#{current_user.nickname}さん , Welcome To Minimal Life", "/users/#{current_user.id}", class: :nav__btn %>
            </div>
            <% else %>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
            
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © MINI ROOM All rights reserved.</p>
    </footer>
  </body>
</html>